[general]
description = "SPAT - SPARK Proof Analysis Tool"
licenses = ["WTFPL"]
maintainers = ["vinzent@heisenbug.eu"]
maintainers-logins = ["Jellix"]

## Long description, can be multi-line using """ """ as delimiters
long-description = """
SPAT - SPARK Proof Analysis Tools
Helper tool to obtain timing information about gnatprove runs (SPARK tools).
"""

## Executables built (must not include any relative path)
executables = ["run_spat"]

## Project files made available to clients (with relative path)
## If only a single project file named as the crate is provided
## at the root directory, then this property can be omitted.
project-files = ["spat.gpr"]

## Keywords for classification
tags = ["spark"]

## A website with further information
website = "https://github.heisenbug.eu/spat"

['1.0.0']
origin = "https://github.com/HeisenbugLtd/spat/releases/download/v1.0.0/spat-1.0.0.tar.gz"
origin-hashes = ["sha512:2750bb27b68346f6585dafcd7b1ccec615200ac96155dd08d05d62505473a2ca5f3fca476c04d4a77a24f6506ada745f3c6a0bcafe4f23f722f3494ba8a1a5c5"]

['1.0.0'.depends-on]
si_units = "^0.1.0"
'case(toolchain)'.system.gnatcoll = ">=19 & <2000"
